eedc_addons/model/base.py
"[Imp] Added the fields salary range and grade"
=> [Imp] Added the fields salary range and grade

company_memo/views/company_memo_view.xml
=> [Fix] Made some fields in view invisible

hr_pms/data/mail_data.xml, hr_pms/models/hr_employee.py
=> [Fix] Error in email sending

hr_cbt_portal_recruitment/data/mail_template_data.xml
[Fix] Fixed the email template
=> Fix Email template

hr_cbt_portal_recruitment/data/mail_template_data.xml, hr_cbt_portal_recruitment/wizard/hr_move_applicant.xml, hr_cbt_portal_recruitment/wizard/hr_move_applicant_wizard.py
[Imp] This is a feature to notify unsuccessful applicants when moving stage.
=> Feat notify unsuccessful applicants

company_memo/__manifest__.py, company_memo/models/config_setting.py, company_memo/security/ir.model.access.csv, company_memo/views/memo_config_view.xml, company_memo/wizard/__init__.py, company_memo/wizard/memo_config_duplication_wizard.py, company_memo/wizard/memo_config_duplication_wizard_views.xml
[Imp] Implemented Config duplication in memo request module
=> Feat memo approval duplicating

hr_cbt_portal_recruitment/models/hr_job.py, hr_cbt_portal_recruitment/security/ir.model.access.csv, hr_cbt_portal_recruitment/static/src/xml/website_hr_recruitment_templates.xml, hr_cbt_portal_recruitment/views/hr_job_views.xml
[Imp] Customizable Proficiency level for job page
=> Feat customizable job page skill proficiency scale

company_memo/models/company_memo.py, company_memo/views/company_memo_view.xml, company_memo/views/memo_forward_view.xml
=> Feat memo statusbar update

company_memo/views/company_memo_view.xml
[Fix] Removed one of the stages in the memo view
=> [Fix] Corrected multiple stages in the memo view

company_memo/models/company_memo.py, company_memo/views/company_memo_view.xml, hr_cbt_portal_recruitment/models/recruitment_request.py
[HOTFIX] Fixes to resolves issues with recruitment
=> [HOTFIX] Fixes to resolves issues with recruitment

hr_cbt_portal_recruitment/security/security_view.xml
[Fix] Tidied up security groups ensuring unknown group will not apply.
=> [Fix] Removed group Interviewer from the security

company_memo/models/company_memo.py, company_memo/views/company_memo_view.xml, hr_cbt_portal_recruitment/views/career.xml
[FIX] Recruitment PEM Form issues
=> [FIX] Recruitment PEM Form issues

hr_cbt_portal_recruitment/__manifest__.py, hr_cbt_portal_recruitment/data/hr_recruitment_data.xml, hr_cbt_portal_recruitment/views/menu_inheritance.xml
[Fix]
I added xml record definition to archive the existing one. So far I did not work but we can still revisit it.
I added base.group_user to the groups to see Recruitment module.
=> Fix recruitment stages

hr_cbt_portal_recruitment/data/hr_recruitment_data.xml
[Fix] Temporarily set noupdate to false to enable updating of the recruitment stages
=> Fix recruitment stagesv2

failed_transformer_repair/__manifest__.py, failed_transformer_repair/models/failed_transformer.py, failed_transformer_repair/models/transformer.py, failed_transformer_repair/security/ir.model.access.csv, failed_transformer_repair/views/failed_transformer_movement_views.xml, failed_transformer_repair/views/menus.xml, failed_transformer_repair/views/tranformer_views.xml
Added stage and some other features
=> [Imp] Added stages

hr_cbt_portal_recruitment/static/src/js/documentation_request.js
[Fix] Solved issue with JavaScript on documentation.
=> [Fix] Solved issue with JavaScript on documentation

company_memo/models/company_memo.py, company_memo/views/company_memo_view.xml, eedc_addons/model/memo_model.py, hr_cbt_portal_recruitment/views/hr_applicant_view.xml, hr_cbt_portal_recruitment/views/hr_job_views.xml, hr_cbt_portal_recruitment/views/hr_recruitment_request.xml
[Fix] To do list:
District on office memo should auto populate employees district by default and set it to readonly
2. Recommended by should be defaulted to the employee initiating this request
3. make required age readonly
4. add nodelete option in addfollowers field
5. On click of 'view / generate recruitment request button ==> Set the stage to approved
6. Requested position should be readonly
7. make checklist add a line to be readonly
=> Fix review issue

company_memo/__manifest__.py, company_memo/data/ir_cron.xml, company_memo/data/mail_templates_data.xml, company_memo/models/company_memo.py, company_memo/models/document.py, company_memo/views/docum.xml
[Imp] Cron jobs for document request
=> Feat document request update

company_memo/models/account_move.py, company_memo/models/company_memo.py, company_memo/models/config_setting.py, company_memo/models/request_line.py, company_memo/models/stock_picking.py, company_memo/security/ir.model.access.csv, company_memo/security/security_group.xml, company_memo/views/company_memo_view.xml, company_memo/wizard/return_memo_wizard.py, eedc_addons/views/hr_memo_view.xml, portal_request/controller/main.py, portal_request/static/src/js/request.js
[Imp] Manually added upgrades.
=> Feat erp manual edits

company_memo/views/company_memo_view.xml, eedc_addons/__manifest__.py, portal_request/static/src/css/portal_css.css, portal_request/static/templates/request_form.xml
Feature to correct button features and added message logs
=> Feat frontend

company_memo/models/company_memo.py, company_memo/security/security_group.xml
this hotfix was to change the validationerror message when non approver users clicks on a button to approve
=> Hotfix main august1

hr_cbt_portal_recruitment/views/survey_template_inherited_view.xml
=> [Fix] Retake of test

hr_cbt_portal_recruitment/views/survey_template_inherited_view.xml
=> [Imp] Showing the scores again

hr_cbt_portal_recruitment/data/mail_template_data.xml
[Imp] Job invitation Email templates.
=> [Imp] Additions to email templates

hr_cbt_portal_recruitment/controllers/main.py
[Imp] Completed time scheduling
=> [Imp] Completed time scheduling

hr_cbt_portal_recruitment/controllers/main.py
=> [Fix] Removed comments

hr_cbt_portal_recruitment/__manifest__.py, hr_cbt_portal_recruitment/controllers/main.py, hr_cbt_portal_recruitment/data/mail_template_data.xml, hr_cbt_portal_recruitment/models/survey.py, hr_cbt_portal_recruitment/views/survey_templates.xml
[Imp] 1. Added a constraint for the survey deadline. 2 Added a check for written tests in _check_validity method in controller
=> Feat applicant importation v2

hr_cbt_portal_recruitment/controllers/main.py, hr_cbt_portal_recruitment/views/survey_templates.xml
[Imp] Added feature the current time
=> [Imp] Added feature the current time

hr_cbt_portal_recruitment/controllers/main.py
=> [Fix] Corrected timing

hr_cbt_portal_recruitment/controllers/main.py
=> [Fix] In progress can continue

hr_cbt_portal_recruitment/views/hr_applicant_view.xml
=> [Fix] additional filters

hr_cbt_portal_recruitment/views/hr_applicant_view.xml
=> [Imp] even more filters in applicants

hr_cbt_portal_recruitment/views/hr_applicant_view.xml
=> [Imp] Filters

hr_cbt_portal_recruitment/models/hr_applicant.py, hr_cbt_portal_recruitment/views/hr_applicant_view.xml, readme.md
[Imp] Added date of birth field in the applicant
=> [Imp] Added a date of birth field in the hr.applicant

hr_cbt_portal_recruitment/data/mail_template_data.xml, hr_cbt_portal_recruitment/models/survey.py, hr_cbt_portal_recruitment/wizard/cbt_schedule_wizard.py, hr_cbt_portal_recruitment/wizard/survey_invite.py, portal_request/static/templates/request_form.xml
[Imp] Added the feature to allow the the applicant being able to be addressed by their name.
=> [Imp] Applicant being addressed by their name in the email

company_memo/views/company_memo_view.xml
[Fix] Removed duplicate 'name' in view
=> [Fix] Removed duplicate field in view

hr_cbt_portal_recruitment/models/survey.py
[Imp] Ability to archive survey input
=> [Imp] Archiving survey input

hr_cbt_portal_recruitment/views/survey_survey_views_inherited.xml, hr_cbt_portal_recruitment/wizard/import_applicants.py
[Fix] Stages and tuple names in importation
=> [Fix] Stages and tuple names in importation

hr_cbt_portal_recruitment/wizard/import_applicants.py
=> [Fix]Error in Applicant importation

hr_cbt_portal_recruitment/wizard/survey_invite.py
[Fix] Adjusted the search domain to get unarchived answers
=> Fix -Domain adjustment of unarchived Answers

hr_cbt_portal_recruitment/wizard/__init__.py, hr_cbt_portal_recruitment/wizard/applicant_send_email.py
[Fix] Adjusted email to send in batches
=> [Fix] Adjusted email to send in batches

hr_cbt_portal_recruitment/wizard/applicant_send_email.py
[Fix] Solves the issue of rotating continuously and some even fail without reporting.
=> [Fix] Queue email in mail.mail

hr_cbt_portal_recruitment/wizard/applicant_send_email.py
=> [Fix] Auto delete

hr_cbt_portal_recruitment/__manifest__.py, hr_cbt_portal_recruitment/wizard/applicant_send_email.py, hr_cbt_portal_recruitment/wizard/applicant_send_mail_views_inherit.xml
[Imp] Gives option for return email
=> [Imp] Gives option for return email
